### ISSUE TITLE
Image not wide enough for IP address

### ISSUE THREAD

**Issue by rdebath** [BastiaanDeHart/Flaming-Wookie#1]
Example:

![image](https://cloud.githubusercontent.com/assets/5853223/7001053/1017d094-dc29-11e4-9b30-ab3206bfa553.png)

**Comment by BastiaanDeHart** [comment]
I see you are using IPv6 and there is no support for IPv6.

**Comment by rdebath** [comment]
:smile: it sure looks like it's supported, the web server has an IPv6 address, it responded on it, it got the remote IPv6 address and formatted it nicely. It didn't even say _unknown_ or ":fearful: WHATS THAT". In fact sometimes it works perfectly ...

![image](https://cloud.githubusercontent.com/assets/5853223/7002842/1069ff48-dc49-11e4-83b8-8677c3d9b6f5.png)

Just not every time… How about an ellipsis if it's more than 26 characters? 
ie: `2001:470:1f09:10d6:5e26:a…`

**Comment by BastiaanDeHart** [comment]
For the IPv6 will I make the image a bit longer. But would I may know which browser you're using and what your user agent is that I'm going to add that that do not have *unknown browser* displays more

**Comment by rdebath** [comment]
The box I connected from was a firewall, so it's a command line tool: `Wget/1.13.4 (linux-gnu)`

Though, now you mention it I could have used a browser:
Lynx: `Lynx/2.8.8dev.12 libwww-FM/2.14 SSL-MM/1.4.1 GNUTLS/2.12.18`
Links textmode: `Links (2.8; Linux 3.10.1-0-amd64 x86_64; GNU C 4.9.1; text)`
Links graphics: `Links (2.8; Linux 3.10.1-0-amd64 x86_64; GNU C 4.9.1; x)`

One weird thing though, Lynx (and Links) managed to download a gzip'd file and think it's a zipped jpeg file rather than a zipped PNG, is that bad ?

**Comment by BastiaanDeHart** [comment]
Thanks, I have the *Links* and *Lynxr* browser added.

**Comment by BastiaanDeHart** [comment]
And I have known the problem that Lynx sees the file as a *gzip* but I find that strange because I have the header in the file to JPEG. This is how I set the file:

*header("Content-Type: image/jpeg");*

**Comment by rdebath** [comment]
The MIME content type for a PNG file is `image/png` so that needs changing.

I think the gzip thing is a content encoding, Google seems to be saying you'd need to do:
`ini_set("zlib.output_compression", "off");`
at the top of your script.

**Comment by BastiaanDeHart** [comment]
I've tried it but it doesn't work
